name = "anime-legacy-api"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CACHE"
id = "TU_KV_NAMESPACE_ID_AQUI"

[vars]
GUILD_ID = "738435000583585823"
CACHE_TTL = 300
